### ISSUE TITLE
Temporarly disable logging

### ISSUE THREAD

**Issue by Cannonb4ll** [owen-it/laravel-auditing#155]
Sometimes, in specific parts of my code, I don't want to audit to log because I do some things in my code to the model that don't have to be logged.

Is there a way to disable auditable on the model in the code temporarly?

Like:

```
public function store(Request $request,)
{
     $model = Model::create($request->all());

     // ## Disable auditing temporarly
     $model->disableAuditing();
   
     // ## Save model to user
     $request->user()->models()->save($model);
}
```

**Comment by quetzyg** [comment]
Hi @Cannonb4ll, sorry for a late reply on this issue.

Can you provide some more details about your specific use case?
Currently, as it stands, me and @anteriovieira feel that this type of feature defeats the whole purpose of the package.

You either want to keep track of all changes that happen to your model or you don't.
This midterm you ask doesn't feel right and if it's for testing purposes, you might as well disable auditing altogether.

Having said that, you can implement your own `Auditor` (`Driver` in the upcoming v4) where you implement the exception logic you see fit or you could just simply add the attributes you don't want audited in the `$dontKeepAuditOf` property (`$auditExclude` in  v4).

**Comment by Cannonb4ll** [comment]
Yes your right, I never saw the ability for disabling updating specific fields with `dontKeepAuditOf`, thank you!

**Comment by kapitannwel** [comment]
i need this and here is my use case:

i have developed an app wherein it can print a qrcode. the value of the qrcode is an encrypted value of an integer field `(my_integer_field)` from the database. the integer value of `(my_integer_field)` is an integer on the database and the encrypted value on the printout only happens during print preview. i need it encrypted so that when it is read by a human eye, it is just a garbage data, but my laravel app can read it and verifiy the information on that paper.

the thing is, we need to print it on a sticker paper. the sticker printer came with its own desktop application. i was able to connect that desktop app on my database. i can generate qrcode by pulling a field from my database.

so i need to create a new field `(encrypted_my_integer_field)` on my database and have it populated with an encrypted value of the integer field `(my_integer_field)` so that that field will be picked up by the sticker printer software and make it the value of the qrcode.

my problem is the 10 thousand rows on my database needs to be populated of the encrypted value of the `(my_integer_field)`. but if i make a routine on my laravel app to populate the encrypted value of my integer field `(my_integer_field)` on the new field `(encrypted_my_integer_field)` this package is running also.

i was able to prevented the update of the `updated_at` field using `$model->timestamps = false;` but i also want to prevent this package from running on a specific query because the laravel app is on use by the end users while i am populating the new field `(encrypted_my_integer_field)`.

any thoughts?

**Comment by kapitannwel** [comment]
i need this and here is my use case:

i have developed a web app wherein it can print a qrcode. the value of the qrcode is an encrypted value of an integer field `(my_integer_field)` from the database. the integer value of `(my_integer_field)` is an integer on the database and the encrypted value on the printout only happens during print preview. i need it encrypted so that when it is read by a human eye, it is just a garbage data, but my web app can read it and verifiy the information on that paper.

the thing is, we suddenly need to print it on a sticker paper. the sticker printer came with its own desktop application. i was able to connect that desktop app on my database. i can generate qrcode by pulling a field from my database.

so i need to create a new field `(encrypted_my_integer_field)` on my database and have it populated with an encrypted value of the integer field `(my_integer_field)` so that that field will be picked up by the sticker printer software and make it the value of the qrcode.

my problem is the 10 thousand rows on my database needs to be populated of the encrypted value of the `(my_integer_field)`. but if i make a routine on my web app to populate the encrypted value of my integer field `(my_integer_field)` on the new field `(encrypted_my_integer_field)` this package is running also.

i need to prevent this package from running on a specific query because the web app is on use by the end users while i am populating the new field `(encrypted_my_integer_field)`.

i hope i was able to explain myself.

any thoughts?

**Comment by kapitannwel** [comment]
good thing that the `disableAuditing()` was adopted as a core feature. thank you as i was able to use it many years after you suggesting it.
