### ISSUE TITLE
Consider supporting UUID for auditable_id

### ISSUE THREAD

**Issue by alexdover** [owen-it/laravel-auditing#183]
I've just installed and used this package, which I think is great and perfect for my use case.

However, I had to make a modification because I am using uuid's for some of the models I wish to audit.

I changed the migration to create the auditable columns as strings:

    $table->string('auditable_id');
    $table->string('auditable_type');

I think the string would then also work for people using integers.

I'd be happy to test it further and put in a pull request?

**Comment by quetzyg** [comment]
Hey @alexdover, thanks for your feedback.

Like yourself, I also do my own changes to the default migration and I believe other people make their own tweaks to serve their project needs.

With that said, I see no point in changing the migration further, since it will never accomodate everybody's needs.

Most use cases should be covered, but it doesn't mean it has to be left untouched.
Feel free to change it where appropriate to suit your needs!
