### ISSUE TITLE
Interface 'OwenIt\Auditing\Contracts\Auditable' not found

### ISSUE THREAD

**Issue by rafalau** [owen-it/laravel-auditing#187]
Olá amigos, boa tarde. Estou feliz por serem brasileiros e terem desenvolvido este plugin fantástico. Consegui implementar o sistema e está a funcionar. Cada vez que uma alteração é feita no sistema, a auditoria correspondente é registrada no DB, porém, não consigo exibi-lás. Seguindo a documentação, me deparei com o seguinte erro: Interface 'OwenIt\Auditing\Contracts\Auditable' not found. Estou utilizando a versão 3.1 no laravel 5.2. Desde já agradeço.

Hi friends, good afternoon. I've been able to deploy the system and it's working. Each time a change is made to the system, the corresponding audit is logged in the DB, but I can not display it. Following the documentation, I came across the following error: Interface 'OwenIt \ Auditing \ Contracts \ Auditable' not found. I'm using version 3.1 on laravel 5.2. Thank you very much in advance.

**Comment by quetzyg** [comment]
Hi @rafalau,

You say you're using version `3.1` of the package, but the namespace you've mentioned (`OwenIt\Auditing\Contracts\Auditable`) is from the upcoming version (4.x), so there's a bit of a mixup.

You probably installed the latest **stable**, but followed the documentation from the development version.

If you want to keep the current version, check the proper [documentation](http://www.laravel-auditing.com/docs/3.1), otherwise update the package to `4.0.x-dev`, with:

```sh
composer require owen-it/laravel-auditing 4.0.x-dev
```
and all should work OK.

**PS:** Eu sou português, o resto da equipa é brasuca 😉

**Comment by rafalau** [comment]
Thank you very much, now it works perfectly.
