### ISSUE TITLE
Queueing does not work

### ISSUE THREAD

**Issue by mgarciadelojo** [owen-it/laravel-auditing#196]
I have already configured my queue system, and got it working using laravel forge. The thing is, when I activate the `queue` flag in the config, it doesn't work. Any piece of advice, please? Thanks!

**Comment by quetzyg** [comment]
Do queues work at all in your setup (for emails and other jobs)?

My advice is, do not use queues.

PS: queue support has been removed from version 4.

**Comment by mgarciadelojo** [comment]
Yes, they do! I use them to send emails and push notifications as well.

Why? It seems a very useful system to get faster responses to users... :(

**Comment by quetzyg** [comment]
Without other information I'm unable to help.

It's unlikely that using queues when auditing will improve performance/responsiveness in such a way that users will be waiting for it to finish. It's just another `INSERT` being executed, that's all.

There's actually a downside, since the queue worker/listener might be unable to resolve the `User`, because the session is usually unavailable in that context.

**Comment by mgarciadelojo** [comment]
Oh, I see, that makes sense... Ok, in that case, I am going to disable that option, because I want to know every step that users follow in my app... Thanks for your help

**Comment by EwertonDCSilv** [comment]
@quetzyg Is there any way to maintain user authentication or send at least the id to these queues?

**Comment by anteriovieira** [comment]
Hi [EwertonDCSilv](https://github.com/EwertonDCSilv), I want to come back with the queues feature soon.

**Comment by EwertonDCSilv** [comment]
> Oi [EwertonDCSilv](https://github.com/EwertonDCSilv) , quero voltar com o recurso de filas em breve.

If you want any help implementing this feature, send me an email!
