### ISSUE TITLE
How to audit service requests?

### ISSUE THREAD

**Issue by gandra** [owen-it/laravel-auditing#239]
Hi!
Your package is great.
I have doubts regarding to the use.
I am developing API backend and I want to audit service requests and model changes as well.
So,
here is what is going on:
1. Client send http request to endopoint1
2. Controller 1 invokes MyService.myMethod()
3. My method do:
   - invoke Model1.save()
   - invoke Model2.delete()
   - invoke Model3.attach([Model4])

so I want to audit MyService.myMethod() request data and eloquent model changes as well. Is it possible?

**Comment by quetzyg** [comment]
Hi @gandra,

The HTTP request itself cannot be audited by the package (by default, that is), since we only cover database events. You could probably get away with a custom audit driver, which has to fetch whatever data the `Request` object has available as soon as the auditing kicks in.

Let me know if that helps and share your results.
