### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by bsormagec** [owen-it/laravel-auditing#258]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.27
| Package version   | 4.0.7
| PHP version       | 7.1.6

Hello I have problem about usage with MongoDB and i fixed it with changing model of audit but it will be fix on new release.

I fixed mongodb usage error like that;

**/src/Models/Audit.php**

Find: 
`use Illuminate\Database\Eloquent\Model;`

Replace:
`use Jenssegers\Mongodb\Eloquent\Model;`

Now its working well but if we change this in package file it will go after package update please add this feature in new release.

**Comment by quetzyg** [comment]
Hi @bsormagec,

Yeah, I'm aware of this, since it was already reported in #211. While the fix seems trivial, it will increase the package setup complexity a little bit.

I don't want to do this change in the current version, so I'm planning this for version 5. I'm gonna mark this as closed, in favour of the older report.

Stay tuned!

Thanks.
