### ISSUE TITLE
Multiple audit tables (one table for model)

### ISSUE THREAD

**Issue by juanpscotto** [owen-it/laravel-auditing#272]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 4.1
| PHP version       |7

#### Actual Behaviour

There is only one audit table for all the models

#### Expected Behaviour (Question)

Is it possible to create other audit tables to log other models?? (one audit table for model).
For example, I have two models Franchise, Branch, and I want them to be audit in audit_franchises and audit_branches respectively.  How Can I achieve that

Thank you.

**Comment by quetzyg** [comment]
Hi @juanpscotto,

Currently we don't support such feature and I don't think we ever will.

The main advantages of the current implementation are:
- Only one table for audits (avoids joining tables when you want to search for a `User`, for example);
- You can still filter by `auditable_type`, so you don't necessarily need to get every audit;
- Your models just need to use the `Auditing` trait, no other setup needed;
- Simplifies configuration;

Any particular reason why you would need separate tables?

**Comment by juanpscotto** [comment]
Because I will use the audits table with an API, so it would be a bottle neck to query all the time just one table. That 's why I need to separate in other tables

**Comment by quetzyg** [comment]
What do you mean a bottleneck? Are you serving 1M requests a day, or something?

**Comment by juanpscotto** [comment]
Yes something like that. It would be a bottleneck.

**Comment by quetzyg** [comment]
Why do you keep saying one table is a bottleneck? Do you have metrics to back that up? Have you considered caching?

But OK, so let's assume you're serving 1M daily requests.
What difference would it make to have separate audit tables?
Do you also have separate user tables (`users_mx`, `users_pt`, ...)?

Also, if you have such a high demand website, your bottleneck is probably that _lonely_ RDBMS that's serving everyone. Because no matter how many tables you create, if you have the traffic you say you have and don't scale, you're fucked. Have you considered moving to a cluster?

**Comment by juanpscotto** [comment]
I don t have the metrics yet. But we are in the planning part of the project. Nop, just une table per type, one user_audits, franchises_audits and so on. If we need to then we ll move to a cluster the DB

**Comment by quetzyg** [comment]
So, you're just in the planning phase and you're already predicting the success of your website? You're probably getting a bit ahead of yourself, don't you think?

In any case, because we now allow custom implementations of the `Audit` model, I guess you could make it work like you want, but you will have to hardcode configuration stuff into your models, since the configuration file is currently designed with one model in mind.

**Comment by juanpscotto** [comment]
Yes, maybe, but I ll try changing the model to see if it works. Thanks

**Comment by lucassena** [comment]
Hi @juanpscotto, do u already have a solution?

I guess [this solution](https://github.com/owen-it/laravel-auditing/issues/255#issuecomment-310921126) from @quetzyg in another closed issue is good.

Probably I'll do it.

This package is awesome, but it was made to fit the standard with just one user model.

Greetings!
