### ISSUE TITLE
There are no commands defined in the "auditing" namespace.

### ISSUE THREAD

**Issue by llmdev** [owen-it/laravel-auditing#280]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
 Framework version | 5.4
| Package version   | 4.1
| PHP version       | 5.6

Error
Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "auditing" namespace.

add provider in app.php

**Comment by quetzyg** [comment]
How can I reproduce this?

**Comment by llmdev** [comment]
I made the installation Via composer

Composer require owen-it / laravel-auditing

I added in app.php the provider

'Providers' => [
    // ...
    OwenIt \ Auditing \ AuditingServiceProvider :: class,
    // ...
]


When I went to execute the command in the terminal

Php artisan auditing: install

Returned the error

Error
Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "auditing" namespace.

**Comment by quetzyg** [comment]
You have `Providers` as key, but it should be all lowercase (i.e. `providers`).

**Comment by quetzyg** [comment]
You never replied if the issue was indeed the `Providers` vs `providers`, but I assume so.

Otherwise it's something else you're doing wrong, since following these steps I don't get any errors:

### Create a new Laravel 5.4 project and require Auditing package:
```sh
composer create-project --prefer-dist laravel/laravel laravel54
cd laravel54
composer require owen-it/laravel-auditing
```

### Register the service provider in `config/app.php`:
Add the `OwenIt\Auditing\AuditingServiceProvider::class` to the `providers` array:
```php
'providers' => [
    // ...
    OwenIt\Auditing\AuditingServiceProvider::class,
    // ...
],
```

### Publish:
```sh
php artisan auditing:install
```

### Get a successful output:
```
Publishing the config files
Publishing the migration file
Successfully installed Laravel Auditing! Enjoy :)
```

**Comment by muhammadn** [comment]
@quetzyg 

Not related because the OP has a typo. For other who might encounter the same problem (with laravel auto-discovery, no need to set providers in config/app.php) and `php artisan auditing:install` not working,

you can do `php artisan vendor:publish`

then select the number with the AuditingServiceProvider (may vary on your laravel installation):
```
[13] Provider: OwenIt\Auditing\AuditingServiceProvider
```

then the config and migration file will be copied.
