### ISSUE TITLE
Multi Authentication support?

### ISSUE THREAD

**Issue by lucassena** [owen-it/laravel-auditing#285]
Hello, I would like to know if the package currently supports several different users (each one is a different guard).

Or some known solution that I can develop using this package?

**Comment by quetzyg** [comment]
If you mean resolving a `User` through several `Guard` classes (`SessionGuard`, `TokenGuard`, etc), it's just a matter of updating the resolver to work with the ones you're using.

The resolver logic could be something like:
```php
// Session
$user = auth()->guard()->user();

if ($user) {
    return $user->id;
}

// Token
$user = auth()->guard('api')->user();

return $user ? $user->id : null;
```

If you mean using multiple `User` models, the official answer is no, since you have to define just **one** `User` model in the configuration.

Related issues: #255 and #272

Read my [answer](https://github.com/owen-it/laravel-auditing/issues/272#issuecomment-315751157) to issue #272 for a possible workaround.

PS: And next time, use the issue template.
