### ISSUE TITLE
Cant resolve user

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#311]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.9
| Package version   | 4.1.3
| PHP version       | 7.0.1

### Description
After updating to 4.1.3, when trying to audit, catch error `Invalid User resolver, callable or UserResolver FQCN expected`
In new config `'resolver' => App\User::class` its ok?

**Comment by quetzyg** [comment]
Hi @rorc,

Firstly, let me tell you that we appreciate your usage of this package. It's great when other people use our code.

Now, I'll have to ask you that before you open new tickets (you've created **6**, so far), that you check the documentation and the GitHub issues. We've put a lot of hours into the documentation, so that it would be easy and straightforward to read and follow.

We also try to document common issues, so that we don't have to repeat ourselves all the time.

Having said that, you should have checked the [installation](http://www.laravel-auditing.com/docs/4.1/installation) section, which mentions the **Resolver**, and read the [configuration](http://www.laravel-auditing.com/docs/4.1/general-settings) documentation on how to implement it.

Closing this issue.

**Comment by rorc** [comment]
@quetzyg Hi, ok, sorry )
