### ISSUE TITLE
On delete audit mark all fields of model as old_values

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#312]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.9
| Package version   | 4.1.3
| PHP version       | 7.0.1

#### Actual Behaviour
When i use call `$model->delete()` with active native trait `SoftDeletes`, all existing fields in model marks as `old_values` and `new_values` becomes empty http://joxi.ru/MAjMLEZcv8NMq2
#### Expected Behaviour
`new_values` and `old_values` remain empty

**Comment by quetzyg** [comment]
Mate, your expected behaviour does not make any sense.

First, you create two issues (#303, #309) due to circumstances where you end up with the `new_values` and `old_values` columns empty when a model is updated with nothing (which by itself is quite remarkable), and now you want to store `Audit` records with empty `new_values` and `old_values` columns, which is exactly what you were complaining about in the first place.

I mean, what the fuck?

**Comment by rorc** [comment]
Yea, i dont want store empty values, but not for delete action...
How else do I remember deleting model?

Here the question is in another: why all fields marks as old_values? It's not necessary at all! Sufficient updating `deleted_at` field...

**Comment by quetzyg** [comment]
>How else do I remember deleting model?

You check the `event` column and realise the value is set to `deleted`.

>Here the question is in another: why all fields marks as old_values?

When the model existed (this would be the **old** state), **all** the attributes were available. Now that the model has been deleted (this is the **new** state), no attribute exists. The `new_values` and `old_values` reflect this.

And before you ask, if you restore the soft deleted model, you just mirror this concept. So, the `old_values` will now be empty because no attributes existed when the model was deleted (obviously), and the `new_values` will have all the attributes, since the model is now available again. Also, the `event` column value will be set to `restored.

I won't discuss this further.

**Comment by rorc** [comment]
Ok, thank) When restored/deleted have to clear `new_values` and `old_values` manually...
