### ISSUE TITLE
question about contracts & implementation

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#332]
- isnt it possible to just use the package by simply including the trait ? why do i have to `implements AuditableContract` for every model ?

- for user model
```php
'user' => [
        'primary_key' => 'id',
        'foreign_key' => 'user_id',
        'model'       => App\User::class,
        'resolver'    => App\User::class,
    ],
```

it should be enough setting a model value and then the package gets it and do its ops internally, this now removes the steps of having to `implements UserResolver` & manually adding
```php
public static function resolveId()
    {
        return auth()->check() ? auth()->user()->getAuthIdentifier() : null;
    }
```

**Comment by quetzyg** [comment]
>isnt it possible to just use the package by simply including the trait ?

No.

>why do i have to implements AuditableContract for every model ?

The question is, why wouldn't you want to implement the needed interfaces?

>it should be enough setting a model value and then the package gets it and do its ops internally, this now removes the steps of having to implements UserResolver & manually adding
```php
public static function resolveId()
    {
        return auth()->check() ? auth()->user()->getAuthIdentifier() : null;
    }
```
What makes you think everyone uses Laravel's `Auth` ?

**Comment by ctf0** [comment]
> The question is, why wouldn't you want to implement the needed interfaces?

because to make things simpler, i make a new trait like
```php
use OwenIt\Auditing\Auditable;

trait revisions
{
    use Auditable;

    protected $auditStrict  = true;
    protected $auditExclude = ['user_id', 'id'];
}
```

and now without any extra steps, i can include this trait in any model and everything works as expected.

**Comment by quetzyg** [comment]
So, instead of a trait, create a `Revisionable` abstract class, which implements the Àuditable` interface. Then, extend that class from the models you need.

**Comment by ctf0** [comment]
> Then, extend that class from the models you need.

what happens if the original model already extends another class ?

**Comment by quetzyg** [comment]
>what happens if the original model already extends another class ? cuz not all extends from Model

I don't know, what do you think will happen?

**Comment by ctf0** [comment]
a class cant extend more than one

**Comment by quetzyg** [comment]
Yes, I'm aware.

**Comment by ctf0** [comment]
> Then, extend that class from the models you need.

i wonder

**Comment by quetzyg** [comment]
Wonder no more:
```php
abstract class Revisionable extends \Illuminate\Database\Eloquent\Model implements \OwenIt\Auditing\Contracts\Auditable
{
    // ...
}
```

```php
class SomeModel extends Revisionable
{
    // ...
}
```

**Comment by ctf0** [comment]
> abstract class Revisionable extends \Illuminate\Database\Eloquent\Model implements \OwenIt\Auditing\Contracts\Auditable

exactly what i meant, i have a class that dont use `\Illuminate\Database\Eloquent\Model` so it means i will have to create a dedicated abstract for it, while the trait works in all cases.

**Comment by quetzyg** [comment]
You do realise that it would take you 1 minute to type `implements Auditable` in the two or three classes you have in your project, and probably another 20 seconds to implement the `UserResolver` in one class, right?

You're also aware that what you're complaining  about is a non problem, correct?

**Comment by ctf0** [comment]
> You're also aware that what you're complaining about is a non problem, correct?

yeap & that's why the title have `question` 😄  , still i didnt mean to get on ur nerve i was simply trying to achieve an easier/shorter approach.

thanx for the help.

**Comment by quetzyg** [comment]
But it's already simple, why complicate, innit?

**Comment by ChrisThompsonTLDR** [comment]
> You do realise that it would take you 1 minute to type implements Auditable in the two or three classes you have in your project, and probably another 20 seconds to implement the UserResolver in one class, right?

> You're also aware that what you're complaining about is a non problem, correct?

I disagree.  Let me explain the situation.  I have a Laravel package called "members."  This package is a membership system that my company uses on 4 or 5 different applications.

The User model for each of these applications likes like:

```
use CompanyName\Members\Models\Traits\MemberUser;

class User extends Authenticatable
{
    use MemberUser;
````

MemberUser traits looks like:

```
//  TRAITS
use Laravel\Scout\Searchable;
use Christhompsontldr\Impersonate\Models\Traits\Impersonatable;
use Christhompsontldr\Laraman\Traits\LaramanModel;
use CompanyName\Segment\Models\Traits\Identifiable;
use Laratrust\Traits\LaratrustUserTrait;
use Illuminate\Notifications\Notifiable;

trait MemberUser
{
    use Identifiable,
        Impersonatable,
        LaramanModel,
        LaratrustUserTrait,
        Notifiable,
        Searchable;
```

By managing the MemberUser trait, I can manage how the User model will act on multiple applications.

Could I add the Audit contract to the User model, sure I could.  But it complicates things because the installation and activation of the Audit package happens inside my Members package.

So, following your suggestion, instead of having Members package manage the installation and activation of Audit, I have to go to all of my applications, update their composer files, update their migrations, update their configs, update their models, do all the testing.

Heaven forbid we have to manage the migration from Audit 4.x (which we are stuck on because of PHP 7 requirements on Audit 5.x) to a newer version.

I'm in the middle of figuring out how to implement Audit for our company.  As it stands, I do not believe we will be able to use the package because of this issue.

**Comment by quetzyg** [comment]
>Could I add the Audit contract to the User model, sure I could. But it complicates things because the installation and activation of the Audit package happens inside my Members package.

It doesn't complicate things, it just makes them more explicit (instead of hiding dependencies in another package).
Or are you gonna tell me that all your projects consist of a single dependency (Members package in this case)? I bet you have other dependencies, so what's wrong with adding one more? You will always have a dependency, the only difference is that it's not a sub dependency.

Also, do you only audit Users? What about other models (Books, Products, Articles, or whatever you may have)?

Tell me frankly, does it make sense to `use` a `MemberUser` trait in a `Book`, `Product` or `Article` model, just to save you a few lines elsewhere? And if so, why would you even do that?

**Comment by ChrisThompsonTLDR** [comment]
>Or are you gonna tell me that all your projects consist of a single dependency (Members package in this case)?

In general, yes.

```
class Membership extends Model
{
    use MemberMembership;
```
```
class Order extends Model
{
    use MemberOrder;
```
```
class Organization extends Model
{
    use MemberOrganization;
```
```
class Plan extends Model
{
    use MemberPlan;
```
```
class Plan extends Model
{
    use MemberPlan;
```
```
class UserMeta extends Model
{
    use MemberUserMeta;
```

We are looking to implement auditing on all these models.

**Comment by quetzyg** [comment]
>In general, yes.

I was referring to the composer dependencies of your project, not models.

As in your project `composer.json` file only having:
```js
    "require": {
        "php": ">=5.6.7",
        "foo/members": "^1.2.3",
    },
```

but then having a `require` object in the `foo/members` composer file with all the dependencies you want to keep hidden from the project `composer.json` for some strange reason.

>I wouldn't use a MemberUser trait on Book. I would use MemberBook on Book.

Sorry, but I still can't see a point in this approach. So when you don't need to audit or use some other functionality that's included in one of those `Member*` traits what do you do? Create a new `MemberBookWithoutAudit` trait? What if you don't want it searchable, but auditable? `MemberBookWithAuditButWithoutSearch` ?

Do you see where I'm getting at?

**Comment by ChrisThompsonTLDR** [comment]
In general, our application's composer includes a few internal packages that we develop.  Those packages include the external packages needed for their functionality.

Our administration package includes Laratrust.  Our billing package includes Braintree's PHP package.

We don't have a case where an application that is including our members package wouldn't also implement any of the packages included.

In the event you have Scout included in Members, but you don't want User to be searchable, there are attributes you can put in the model to make that happen.

Feel free to skype me (same username as on github) if you have questions.  We'd really like to use Audit, but won't unless it can be included in a package.  I'm moving to testing other auditing/revisioning package, but wanted to use Audit as our first choice.

For reference, we do this with Scout, Laratrust, Billable, Laraman, Hashids, Impersonate and Log viewer packages.

Audit is the first package I've encountered where I couldn't include it in a package.

**Comment by quetzyg** [comment]
Scout has a `Searchable` interface, how do you manage that, then?

**Comment by ChrisThompsonTLDR** [comment]
Searchable is a trait.

```
class Post extends Model
{
    use Searchable;
```

**Comment by ChrisThompsonTLDR** [comment]
VentureCraft rewrote Revionable to so the use case we are discussing here.

https://github.com/VentureCraft/revisionable#the-new-trait-based-implementation

**Comment by quetzyg** [comment]
Like I stated before, this is a **non** issue. You're just abusing the way traits are supposed to be used.

You can definitely use traits like that, by hiding imports and make it look _nicer_, but you'll end up with more files than you would need to.

Today it's this package, tomorrow it will be some other, and in the end, you'll have to rely on subpar implementations because you didn't want to implement an interface, just to make it look _nice_.

Best of luck, to you and whoever else will end up maintaining those applications.
