### ISSUE TITLE
Entry in audits table created if non-audited model attribute changed

### ISSUE THREAD

**Issue by advicepyro** [owen-it/laravel-auditing#396]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.34
| Package version   | 6.0.1
| PHP version       | 7.1.11

#### Actual Behaviour

This package is creating new audit entries for changes to model attributes which I've explicitly excluded from auditing. In the new audits row in the database, both `old_values` and `new_values` contain `[]`

In the context of my application, this is leading to a lot of unnecessary entries in our audits table, as we modify a non-audited field in our model somewhat frequently.

#### Expected Behaviour

A new audits entry should not be included, or this behaviour should be configurable.

#### Steps to Reproduce

* Define fields in a model's `$auditInclude`
* In tinker, alter a model attribute that is not included in the above, then call `save()`
* Check the newest entry in the audits table

#### Possible Solutions

For now I'm overriding my model's `save()` to temporarily turn off auditing with `disableAuditing()` prior to calling the model `save()`.

**Comment by quetzyg** [comment]
>This package is creating new audit entries for changes to model **attributes which I've explicitly excluded** from auditing.

The idea is to exclude certain fields from the audit, not to prevent auditing.

>In the new audits row in the database, both old_values and new_values contain **[]**

So what you're reporting is in fact expected behaviour. Think of more sensitive data that you don't want to include, but you still want to audit everything else.

Also, an audit is not just the model attributes that changed. It's also the metadata (User-Agent, IP, URL, the User that made the changes or the date when all that happened).

This has been previously discussed at least in #263, #292 and #303.

**Comment by advicepyro** [comment]
That's fair. I'll keep the workaround in place for our application, as in our case the UA/IP/URL isn't too important (99% of the time the data is the same).
