### ISSUE TITLE
Transaction fail event still fired to websocket

### ISSUE THREAD

**Issue by aqualaguna** [owen-it/laravel-auditing#414]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.4.x
| Package version   | 6.0.0
| PHP version       | 7.0.1

#### Feature
I'am using event listener to listen to OwenIt\Auditing\Events\Audited event and firing it to websocket to other user. and when the transaction fail mean database rollback. the event still fired and the data sent through web socket.
making the data not valid. can the laravel audit add for compability for DB::transaction() or DB::beginTransaction() ?

**Comment by quetzyg** [comment]
Hi @aqualaguna ,

That's something you'll have to handle yourself, because at the point in time the `OwenIt\Auditing\Events\Audited` is fired, everything in OK. Remember that the auditing kicks in on `created`, `updated`, `deleted`, `restored` and `retrieved` events, which means the data was persisted to the database.

From that point on, if you're running more queries inside a `DB::transaction()`, you probably have to fire your own event at the end of all that, to ensure everything went smoothly and then, you can notify the user via web socket.

**Comment by quetzyg** [comment]
I'm gonna close this issue, but feel free to comment if needed.

**Comment by aqualaguna** [comment]
even the auditing record is gone after i roll back. so i think its not persisted in database after rollback.
