### ISSUE TITLE
Globally disable auditing

### ISSUE THREAD

**Issue by rankarpan** [owen-it/laravel-auditing#435]
There are cases where we don't want to audit while testing, running migrations, etc... There needs to be a way to turn auditing off and on.

**Comment by andreshg112** [comment]
Is there a way to disable in the config file or .env? @quetzyg

**Comment by quetzyg** [comment]
Hi @andreshg112, 

If you mean disabling the auditing functionality entirely, no, this package doesn't allow for that.

Refer to the [Auditable Configuration](http://www.laravel-auditing.com/docs/9.0/auditable-configuration), more specifically the `Enable/Disable` section.

**PS:** I'm no longer a collaborator here, since I started my own auditing package.
