### ISSUE TITLE
Tenant base application ,so want to add one or two more fields to audit table

### ISSUE THREAD

**Issue by rockers007** [owen-it/laravel-auditing#444]
We are working on tenant base application ,so want to add one or two more fields to audit table.
Please guide use how to do this

**Comment by quetzyg** [comment]
First of all, use the issue template when submitting an issue. Don't just ignore it, because it's there for a reason.

In regards to your question, add the extra columns you need to the audit table. Then, you'll have to override the `toAudit()` method from the `Auditable` trait, so that the new columns are also filled.

**Comment by rockers007** [comment]
Thank you
