### ISSUE TITLE
Audits table: 15GB

### ISSUE THREAD

**Issue by paulocastellano** [owen-it/laravel-auditing#459]
Hello, my audits table have around 15GB in only 6 months of use. 

Any sugestion about it? I think in compile it, save in any.txt and send to s3 everyday at 03:00 for example.

**Comment by quetzyg** [comment]
Please follow the rules.

**Comment by quetzyg** [comment]
Last call before closing this.

**Comment by nedf23** [comment]
Which rule(s) has been broken?

I don't see anything regarding this in the installation, general configuration or troubleshooting section. I also tried looking through closed issues and didn't find any obviously related to this question. The issue template link is broken on the problems page too.

I'm curious about this as well. Looking to take on a large project that will have a lot of audit records and the database audit table will grow quickly.

**Comment by quetzyg** [comment]
When you [create](https://github.com/owen-it/laravel-auditing/issues/new) a new issue, it already comes pre filled with the template, which you only have to finish filling it up with information (so we can actually help, you know?). A lot of effort has been put so that we don't have to do all this back and forth, but sometimes people just ignore and do it their own way.

**Comment by nedf23** [comment]
Ah, I see now. Wasn't aware of that. Thanks!

**Comment by quetzyg** [comment]
In any case, you can prune `Audit` records. Check how [here](http://www.laravel-auditing.com/docs/8.0/auditable-configuration).
