### ISSUE TITLE
Dynamic update of audits

### ISSUE THREAD

**Issue by jadamec** [owen-it/laravel-auditing#518]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel|Lumen
| Framework version | 5.8.y
| Package version   | 9.2.0
| PHP version       | 7.3.y

#### Expected Behaviour

Hello there, is possible to "generate" audits in this way, please? Only to update 'new_values' of previous one if that update was done in range of let's say 5 minutes from the main one. Now, there're dozens of audits with the same parameters and only the values are changed (the same things happen for example when someone writes wrong phone number and updates it immediately). Thanks.
- https://youtu.be/E7RGLIl-JO0

**Comment by themightystephen** [comment]
If you're willing to play around with customising some things, you could potentially try making your own Auditable trait which itself uses the existing Auditable trait (I assume that's possible in PHP) and have that override the `Auditable::readyForAuditing()` method of `/src/Auditable.php` to check the time of the most recent audit entry for the current model and if it's too soon, it skips the audit (returns `false`). You could then have your models all use your custom Auditable trait instead of the standard one. Untested idea but something you could look into.

**Comment by parallels999** [comment]
You could get the last audit and check time, if that update was done 5 minutes from the main one disable auditing
