### ISSUE TITLE
The user_type and user_id is null

### ISSUE THREAD

**Issue by GTHell** [owen-it/laravel-auditing#528]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.*
| Package version   | ^9.2
| PHP version       | 7.2.14

#### Actual Behaviour

When doing the CRUD on any model that implements the audit package got recorded in Audit table with the _user_type_ & _user_id_ is null

#### Expected Behaviour

Expect user_type & user_id to be not null.

#### Steps to Reproduce

- Create a new Laravel project
- Follow the installation guide from the package document
- Create a Post model, controller, and view for testing
- implement an audit contract in Post model
- Test the create, update, delete 
- Check database

**Comment by neoacevedo** [comment]
Same issue. I have well configured (?) my guards in audit config.

**Comment by Peter-Krebs** [comment]
@GTHell Have you resolved this? Can the issue be closed?

As @neoacevedo has shown you might have needed to configure the used guards as well.  
See `config/auth.php` in `['guards' => [...]]` where your guards must be in place. Maybe `['defaults' => 'guard']` is missing or incorrect?  
I believe the routes must have the correct middleware set to use the guards. Otherwise the user object might not be gotten by `Auth::guard()` and Audit cannot resolve the user for you.

In case you are interested, add a breakpoint or a `dd` call in `OwenIt\Auditing\Resolvers\UserResolver.php` which will be called by default to get the user object. The default implementation just calls `Auth::guard($guard)->user()` as is usual for Laravel AFAIK.

**Comment by kapitannwel** [comment]
i was able to solve this by adding a `guards` entry. this is because i created a custom `admin.php` route file.

so now i have this:

```
'user'      => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'api',
            'admin'
        ],
        'resolver'     => OwenIt\Auditing\Resolvers\UserResolver::class
    ],
```

after this, the `user_type` and `user_id` fields got value.

hope this helps.
