### ISSUE TITLE
Empty audit records

### ISSUE THREAD

**Issue by chinleung** [owen-it/laravel-auditing#585]
| Q                 | A
| ----------------- | ---
| Bug?              | Yes
| New Feature?      | No
| Framework         | Laravel
| Framework version | v6.18.3
| Package version   | v9.3.2
| PHP version       | 7.4.3

#### Actual Behaviour

I have the audit setup for my `App\User` model, which has a column named `last_login_at`. However, we do not want to track that change in the audit, so we've added the following to our model:

```php
protected $auditExclude = [
    'last_login_at',
];
```

Now whenever a user sign in, instead of not recording it in the audit, we have a record similar to this

| event | auditable_type | auditable_id | old_values | new_values
| ----------------- | ----------------- | ----------------- | ----------------- |---
| updated | user | 1 | [] | []

#### Expected Behaviour

We'd expect the package to not write any audit at all.

#### Steps to Reproduce

Add a listener in the `EventServiceProvider` for the `Authenticated` event.

```php
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        Authenticated::class => [
            SaveLastLogin::class,
        ],
    ];
}
```

And then in the listener, simply update the timestamp column.

```php
class SaveLastLogin
{
    public function handle($event)
    {
        $event->user->update(['last_login_at' => now()]);
    }
}
```

#### Possible Solutions

Don't create an audit record if both `old` and `new` values are empty.

**Comment by garethlawrence** [comment]
Any updates workarounds?

**Comment by mpemberton5** [comment]
same issue, even though I have a field in $auditExclude, it still writes empty old/new values.

| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.11.0
| Package version   | 10.0.0
| PHP version       | 7.2.24

#### Actual Behaviour

In App\User, I have excluded three fields using the $auditExclude property.  Upon updating any of the three fields, it will trigger an audit, but write no values.

```
protected $auditExclude = [
                           'last_ping',
                           'idle_since',
                           'last_url',
                          ];
```


#### Expected Behaviour

Expected behavior is to not write a record to the audit table where both old_values and new_values fields are empty.


#### Steps to Reproduce

Here's the function that runs that updates the fields.  It is in the UsersController.


```
    public function keepalive($url, $dt)
    {
        if (auth()->check()) {
           $u             = auth()->user();
            $u->last_ping  = date('Y-m-d H:i:s');
            $u->idle_since = $dt;
            $u->last_url   = $url;
            $u->save();
        }
    }
```

I performed some additional testing and confirmed it isn't specific to a data type.  I disabled all but one field, iterating through each and they all produced a new audit record (like below), but with no values.

![image](https://user-images.githubusercontent.com/286273/82513714-c7492480-9ae1-11ea-80bc-6783a4c3b602.png)

**Comment by mpemberton5** [comment]
Found the fix.  [Per the Developer](https://github.com/owen-it/laravel-auditing/issues/263#issuecomment-330695869)


> Try adding an observer in the `boot()` method of the `AppServiceProvider`:
> 
> ```
> Audit::creating(function (Audit $model) {
>     if (empty($model->old_values) && empty($model->new_values)) {
>         return false;
>     }
> });
> ```
